### ISSUE TITLE
libs size

### ISSUE THREAD

**Issue by xiaoxiaoying** [itzharDev/MuPDF#1]
Why libs so big?The compiler mupdf package size is 9.12,I compile the package size is the same to you

**Comment by itzharDev** [comment]
Lib compiled for 3  different compilers architectures, if u have any way to reduce it - please tell me

**Comment by xiaoxiaoying** [comment]
try add LOCAL_CFLAGS += -DTOFU in Core.mk

**Comment by itzharDev** [comment]
Thanks!
